train_file: ["./data/snli-ve/ve_train.json"]
val_file: "./data/snli-ve/ve_dev.json"
test_file: "./data/snli-ve/ve_test_main_1k.json"
image_root: "./data/flickr30k/flickr30k-images/"

bert_config: "./tmm_scc/configs/config_bert.json"
image_res: 384
vision_width: 768
embed_dim: 256

batch_size_train: 8
batch_size_test: 8

epsilon: 12
num_iters: 10
alpha: 0.4

distill: false
warm_up: true
optimizer: { opt: adamW, lr: 1e-5, weight_decay: 0.02 }
schedular:
  {
    sched: cosine,
    lr: 1e-5,
    epochs: 10,
    min_lr: 1e-6,
    decay_rate: 1,
    warmup_lr: 1e-5,
    warmup_epochs: 1,
    cooldown_epochs: 0,
  }
